// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOhZYllfXkHw5JUVP5BI4qiP8ISpceo6E',
    appId: '1:39237261880:web:abdd2f329a422eace3a4cd',
    messagingSenderId: '39237261880',
    projectId: 'jawara-kelompok3-77166',
    authDomain: 'jawara-kelompok3-77166.firebaseapp.com',
    storageBucket: 'jawara-kelompok3-77166.firebasestorage.app',
    measurementId: 'G-FGZYRKH962',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-OmZQWiwJX0HgiJVMBkYHZkoKiT1Yp8',
    appId: '1:39237261880:android:baf3aad47e7d6e50e3a4cd',
    messagingSenderId: '39237261880',
    projectId: 'jawara-kelompok3-77166',
    storageBucket: 'jawara-kelompok3-77166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd5c6d0a2iOH6L2UEn33WL0QkraZSJSAI',
    appId: '1:39237261880:ios:5fbe4995bfe1e265e3a4cd',
    messagingSenderId: '39237261880',
    projectId: 'jawara-kelompok3-77166',
    storageBucket: 'jawara-kelompok3-77166.firebasestorage.app',
    iosBundleId: 'com.example.jawaraKelompok3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd5c6d0a2iOH6L2UEn33WL0QkraZSJSAI',
    appId: '1:39237261880:ios:5fbe4995bfe1e265e3a4cd',
    messagingSenderId: '39237261880',
    projectId: 'jawara-kelompok3-77166',
    storageBucket: 'jawara-kelompok3-77166.firebasestorage.app',
    iosBundleId: 'com.example.jawaraKelompok3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOhZYllfXkHw5JUVP5BI4qiP8ISpceo6E',
    appId: '1:39237261880:web:bf70e4b0d77c6bc2e3a4cd',
    messagingSenderId: '39237261880',
    projectId: 'jawara-kelompok3-77166',
    authDomain: 'jawara-kelompok3-77166.firebaseapp.com',
    storageBucket: 'jawara-kelompok3-77166.firebasestorage.app',
    measurementId: 'G-69MC9MY6RK',
  );
}
